# Generated by Django 5.2.11 on 2026-03-09 06:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('name', models.CharField(help_text='模板名稱', max_length=100)),
                ('description', models.TextField(blank=True, help_text='模板說明')),
                ('schema', models.JSONField(help_text='Faker 生成規則定義')),
            ],
            options={
                'verbose_name': '自定義模板',
                'verbose_name_plural': '自定義模板',
                'db_table': 'mock_data_custom_schema',
                'ordering': ['-created_at'],
            },
        ),
    ]
